language: node_js
node_js:
  - 10
services:
  - docker
env:
  global:
    - PACT_BROKER_BASE_URL=https://lmayo.pactflow.io
    - PACT_BROKER_PUBLISH_VERIFICATION_RESULTS=true
    # Encrypted PACT_BROKER_TOKEN
    - secure: "G9ZZZfscSBICqt0UZ6uIZVEDER72l+bXSnhGGf9GN+nWbRkW4zdBXCHYQbmXvmLOn6MCC1+L2CjNhl/MZiSLaoNBcMRW0xuO3T42B6Ue08+TaliPp57Xxt5hdtGTNN43squPg1pOfrYY7zzDmoCMJx6Ca2YTrnragjfAs3nJCyUAETGdWt3hjsN1yYbHvtIl3ODx5SY34YxOO8cqKaZn/cQdjxQb4BY8getQt++LlQXWRiguwkPVHZ0KOqDYl9AUr3oq5Eq0SEBLMyVzA4BmZDC6Hs7BYG5VQyyrjsqOL2fMVsqZHaHmRghpR13IJgVTo7HoYZw4OyS/+Daobfrx+VOwM8Nl88OlUmT/rR9+KLzjYd/7+/z74KKXxXEzBr5akhaCfe2GhLuNz2BHEFgzJLSrrxYqUcArSKTIig/GI0SIQ6hG44OyC0aRwds2EKIsfmhGG007K7KanpAleWtBvUnL/Lv+qIg+zdx8WcmdJ7baNzy1HrICsldoj2ZXiCflFxLMnsoMMbUDtynew9GRaiioGhj8NgAa3QqmkoL5Pu/O7rPodTLUANAP/NC+bLCv/kIt2W6VVQNHq9sjGQLxOoCxe9Dx70stY++0n+eNbWv4hmZUIGEgcASyjnRcxoSg8oegt8uVVeKxrFaci/C6JCBzT/PTAfkvRcqZjfCQvSE="
before_script:
  - docker pull pactfoundation/pact-cli:latest
script:
  # When a webhook triggers a build, the PACT_URL will be set. In this case, just run the verification step.
  # Otherwise, run the normal build.
  # This is just to get around the fact that Travis CI only has one build definition per repository.
  # Normally you would define a separate job for the webhook triggered verification.
  - >
    if [ -n "${PACT_URL}" ]; then
      make ci_webhook
    else
      make ci
    fi
